### ISSUE TITLE
Investigate if Traefik slows down our application. 

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#105]
We have a suspicion that Traefik slows down the application.
Therefore we need to find out if its much faster without Traefik. It is possible that its the Https part that is slow.

**Comment by Hjaltesorgenfrei** [comment]
After some testing by @jlndk we found out that it is horrible slow. He will hopefully post some benchmarks.

**Comment by jlndk** [comment]
With Traefik:
![unknown](https://user-images.githubusercontent.com/3009101/76529490-a5dd1400-6472-11ea-8efb-b9e0336a9e00.png)
Without Traefik:
![unknown (1)](https://user-images.githubusercontent.com/3009101/76529532-b42b3000-6472-11ea-81e1-7fa8f3724465.png)

**Comment by jlndk** [comment]
Conclusion: Traefik is slow, and we need to remove it
