### ISSUE TITLE
OpenAPI specification for our API

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#111]
Currently all of it is implicit, it should be explicit to help with lowering development time.

**Comment by jlndk** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-3.1

**Comment by tobloef** [comment]
I'm also interested in this if Hjalte doesn't do it.
