### ISSUE TITLE
Action to generate artifacts

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#19]
We should have an action to generate artifacts. Doing this should help us with setting up CD later.

**Comment by jlndk** [comment]
~~Burde kun ske ved opdateringer til master branch (med mindre vi vil lave pre-releases, hvilke nok kræver en mere advanceret branching strategi)~~
Should only happen on opdates to the master branch (unless we want to do pre-releases, which would require a more advanced branching strategy.
