### ISSUE TITLE
Rewrite minitwit.py in C#

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#26]

**Comment by Jakobis** [comment]
We need to add Authentication to the app. I looked into using Identity, which currently seems like the best bet, since it is heavily tied into to EntityFrameworkCore, and the primary recommendation from Microsoft when writing C#. I think it should wait until we are done with getting EFC to work.

**Comment by tobloef** [comment]
re: Authentication.

I know that the whole ASP.NET ecosystem can be a bit daunting. I remember struggling a bit with Identity (høh) back in the day, when I had to make something with ASP.NET. But I don't remember enough to be of much use lol. So don't feel too bad if you have to bash your head against it for a bit. I'll try to help if you request it, though from what I heard from Hjalte, you're doing good.
