### ISSUE TITLE
Adapt control.sh

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#3]
Adapt the shell script control.sh according to the recommendations of the tool shellcheck (a linter for shell scripts)

`shellcheck control.sh`

You can install the tool via: `sudo apt install shellcheck`

**Comment by jlndk** [comment]
~~Måske også værd at integrerer i vores CI workflow~~

Maybe also worth integrating into our CI workflow.

**Comment by Hjaltesorgenfrei** [comment]
~~Enig, burde ikke være svært at lave en action til det.~~

Agreed. Should not be hard to make an action for it.

**Comment by jlndk** [comment]
~~Manual lukning siden "Fixes issue #3" (sadly) ikke lukkede issuet automatisk.~~
Manual close since "Fixes issues #3" (sadly) didnt close the issue automaticly.
