### ISSUE TITLE
Creation of application following API spec

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#34]
We have a new [API Spec](https://github.com/itu-devops/2020-spring/blob/master/sessions/session_02/API%20Spec/minitwit_sim_api.py) to follow.  This is appears to be a new application and does require changes in the main application.
It has the following functions:

- [GET] "/latest", returns latests messages
- [POST] "/register", different from the other main application as it does not return a rendered template.
- [GET] "/msgs", returns some messages.
- [GET, POST] "/msgs/<user>", get messages for user or post new messages for them
- [GET, POST] "/fllws/<user>", get follows for user or follow new user

**Implementation** of this should probably wait until after the main application is up and running as it will use many of the same functions. 
Hosting of this application probably needs to be on another port, as it also uses the "register" and we cant add a "/api" before. Maybe we can host it on api.\*.\* for this and the main application on www

**Comment by Duckapple** [comment]
Rest of following this spec requires the website to display messages and follows, before routing can happen.

**Comment by Hjaltesorgenfrei** [comment]
I dont think it should return a view. The spec returns json.
