### ISSUE TITLE
Adapt MakeFile/Flagtool for Ubuntu 18.04

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#4]
Adapt the command in the Makefile that builds the flag_tool. Likely, the shared library is located in a different place, and after installing libsqlite3-dev you might not necessarily have to specify it explicitly.

Check the runtime dependencies of your compiled flag_tool with the ldd command:

`    ldd ~/Desktop/itu-minitwit/flag_tool`

**Comment by jlndk** [comment]
Manually closing the issue since it was not detected automaticly "Flag tool fix. #4".
