### ISSUE TITLE
Rest-API

### ISSUE THREAD

**Issue by Jakobis** [jlndk/devoops#44]
The API which will be used to test our program. (This will be split into multiple tasks)

**Comment by jlndk** [comment]
The API should comply with these specs https://github.com/itu-devops/2020-spring/blob/master/sessions/session_02/API%20Spec/minitwit_sim_api.py.

Once complete #52  should be performed to make sure we comply to spec

**Comment by Hjaltesorgenfrei** [comment]
Was this not a duplicate issue of #34?

Spec:
- [GET] "/latest", returns latests messages
- [POST] "/register", different from the other main application as it does not return a rendered template.
- [GET] "/msgs", returns some messages.
- [GET, POST] "/msgs/<user>", get messages for user or post new messages for them
- [GET, POST] "/fllws/<user>", get follows for user or follow new user
