### ISSUE TITLE
Flag twit tool

### ISSUE THREAD

**Issue by Jakobis** [jlndk/devoops#51]
There should be an action for it in the repository and there must be a Command line app

**Comment by Hjaltesorgenfrei** [comment]
Currently you can use the update message. But its not ideal.

**Comment by jlndk** [comment]
To be more specific the flagtool already exists (courtesy of #30). It does however use raw sql statements and should therefore be rewritten using ef core (the repositories).

Futhermore the tests should also be updated to be compatible (still using a in-memory db) .
