### ISSUE TITLE
Add subdomain to access the API

### ISSUE THREAD

**Issue by Duckapple** [jlndk/devoops#76]
https://stackoverflow.com/questions/20609776/asp-net-mvc-subdomains is an answer

**Comment by Hjaltesorgenfrei** [comment]
Could you explain the value that is given from this?

**Comment by jlndk** [comment]
An alternative would be to separate the API into another server process and use a reverse proxy to delegate the traffic. The main advantage of this is the decoupling of the API and web app (both in terms of scalability and resiliency), though with increased complexity. To be more specific this would simply require extracting the API into a separate dot net app, make another docker image for that web app, and add a reverse proxy such as nginx, traefik or HAProxy (which would also be a third docker image).

In the current state of the project I don't think it is worth doing yet, but if we want to achieve more resiliency and scalability we should consider this (especially if we're considering scaling the service across multi server machines).

**Comment by jlndk** [comment]
Now that we use traefik (courtesy of #83) this is now possible. However this would still require extracting the API controllers into a separate container.
