### ISSUE TITLE
Profile pictures.

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [jlndk/devoops#84]
The profile picture string is hardcoded, we might want to make it depend on username.

**Comment by Duckapple** [comment]
I think gravatar works by email rather than username, but I agree.

**Comment by jlndk** [comment]
According to [Creating the Hash](https://en.gravatar.com/site/implement/hash/), from gravatars own website and [using gravatar in classic ASP](http://www.webdevbros.net/2007/12/29/using-gravatar-in-classic-asp/), which is linked from the official gravatar.com website, we should simply md5 the users email, and use that as the parameter
